# Generated by Django 5.2.8 on 2026-02-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
