# Generated by Django 5.2.8 on 2026-02-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_venda_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data',
            new_name='data_venda',
        ),
    ]
